version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: demandas_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demandas_db
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: demandas_backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=demandas_db
      - DB_PORT=3306
      - PORT=5000
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: demandas_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
